name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        If this is your first time contributing, we recommend you read the [bug reporting guide](https://kai-beckers.gitbook.io/subnautica/bug-reporting)
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: How can you reproduce this?
      description: "Tell us how this happened. If you don't know, leave this empty."
      placeholder: "Input here."
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating system
      description: "What OS did this happen on? Make sure to include the OS version (e.g. macOS 10.15.7)"
      placeholder: "Windows 10"
    validations:
        required: true
  - type: dropdown
    id: mod
    attributes:
      label: Mod
      description: What mod is causing this?
      options:
        - Catwalks
        - Abandoned Bases
        - More Compartments
        - Base Alarms
        - Decorations Mod port
        - More Foods
        - Base Library
        - Snapping Library
    validations:
        required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the mod are you running? If you are running an outdated version, try installing an newer version to see if it has been resolved already.
      placeholder: "Version"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. You can find your log files in directory you copy & pasted QMods in. See the [bug reporting guide](https://kai-beckers.gitbook.io/subnautica/bug-reporting).
      render: shell
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Extra information
      description: If you want to add anything, you can do so here.
      placeholder: Start writing here...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
