name: Crash Report
description: Report & get support for crashes.
labels: ["crash"]
body:
  - type: markdown
    attributes:
      value: | 
         ## Crash Reports
         Make you read the [common issues list](https://github.com/kaibeckers/mymods/issues/4) first.
         Thank you for taking the time to fill out this report! This form is mainly intended for getting support and reporting crashes to the developers.
  - type: textarea
    id: whathappened1
    attributes:
      label: What did you do just before the crash?
      description: "List all the possible reproduce steps. This is necessary for us to find the issue."
    validations:
      required: true
  - type: input
    id: operatingsystem1
    attributes:
      label: Operating System
      description: "What OS did this happen on? Make sure to include the OS version (e.g. macOS 10.15.7)"
      placeholder: "Windows 10"
    validations:
        required: true
  - type: dropdown
    id: mod
    attributes:
      label: Mod
      description: What mod is causing this?
      options:
        - Catwalks
        - Abandoned Bases
        - More Compartments
        - Base Alarms
        - Decorations Mod port
        - More Foods
        - Base Library
        - Snapping Library
    validations:
        required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. You can find your log files in directory you copy & pasted QMods in.
      render: shell
    validations:
      required: false

